"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),view=require("../../shared/accounting/activity-accounting-view-model");
const plan={playerFee:1000,requiredPlayerCount:6,vendorBaseAmount:6000,playerIds:["a","b","c","d","e","f"],vendor:{displayName:"測試店家"},feeItems:[{feeItemId:"fee-1",title:"指定費",amount:300,allocations:[{personId:"a",amount:300}]},{feeItemId:"fee-2",title:"特殊費用",amount:200,allocations:[{personId:"a",amount:100},{personId:"b",amount:100}]}]};
const transactions=[{transactionId:"meal",type:"expense",title:"餐費",amount:1500,paidBy:"a",splitStatus:"completed",splits:["a","b","c","d","e","f"].map(personId=>({personId,amount:250,settlementStatus:personId==="a"?"settled":"pending"}))},{transactionId:"drink",type:"expense",title:"飲料",amount:600,paidBy:"b",splitStatus:"pending",splits:[]}];
const build=(patch={})=>view.build({feePlan:plan,memberPayments:[],vendorPayments:[],transactions,pairwiseTransfers:[],pendingActions:[],personIds:["a","b","c","d","e","f"],currentPersonId:"a",...patch});

test("店家基本費與額外費形成同一店家應收 Projection",()=>{const result=build();assert.equal(result.store.baseAmount,6000);assert.equal(result.store.perPersonFee,1000);assert.equal(result.store.fixedBillingHeadcount,6);assert.equal(result.store.extraAmount,500);assert.equal(result.store.receivable,6500);});
test("店家未支付金額不進 Activity Current Total",()=>{const result=build();assert.equal(result.store.actualPaid,0);assert.equal(result.activity.currentExpense,2100);});
test("店家部分付款後只將實付部分加入 Current Total",()=>{const result=build({vendorPayments:[{kind:"payment",amount:3000}]});assert.equal(result.activity.storeActualExpense,3000);assert.equal(result.activity.currentExpense,5100);assert.equal(result.store.outstanding,3500);});
test("店家退款從 Current Total 扣回且原付款仍保留",()=>{const payments=[{paymentId:"p1",kind:"payment",amount:6500},{paymentId:"r1",kind:"refund",amount:500}],result=build({vendorPayments:payments});assert.equal(result.store.actualPaid,6000);assert.equal(result.activity.currentExpense,8100);assert.equal(result.store.payments.length,2);});
test("玩家額外 Transaction 加入 Activity Total，Split 與 Settlement 不重複增加",()=>{const base=build(),withSettlement=build({pairwiseTransfers:[{fromPersonId:"b",toPersonId:"a",amount:250}]});assert.equal(base.transactions.actualExpense,2100);assert.equal(withSettlement.activity.currentExpense,base.activity.currentExpense);});
test("Person Expense 同時包含店家 Share 與 Transaction Split",()=>{const person=build().currentPerson;assert.equal(person.totalExpense,1650);assert.deepEqual(person.sources.map(item=>item.title),["劇本費","指定費","特殊費用","餐費"]);});
test("人物明細 V2 只投影玩家 Transaction Split，不重複店家費用",()=>{const person=build().currentPerson;assert.deepEqual(person.playerSources.map(item=>item.title),["餐費"]);assert.equal(person.playerTotalExpense,250);assert.equal(person.playerPaidAmount,1500);assert.equal(person.playerPaidDefinition,"transaction_payments_plus_settled_outgoing_settlements");});
test("人物明細淨支付扣除已正式收回但不改變 Pairwise 淨結果",()=>{const person=build({transactions:[{transactionId:"drink",type:"expense",title:"飲料",amount:350,paidBy:"a",splits:[{personId:"a",amount:87}]}],settledReceivedByPerson:[{personId:"a",amount:87}],pairwiseTransfers:[{fromPersonId:"a",toPersonId:"b",amount:115}]}).currentPerson;assert.equal(person.playerPaidAmount,350);assert.equal(person.playerReceivedAmount,87);assert.equal(person.playerNetPaidAmount,263);assert.equal(person.playerTotalExpense,87);assert.deepEqual([person.playerPosition,person.playerNetAmount],["payable",115]);assert.equal(person.playerNetPaidDefinition,"player_paid_amount_minus_settled_incoming_settlements");});
test("人物明細應付應收只採正式 Pairwise 關係，Split 不冒充付款",()=>{const payable=build({memberPayments:[{personId:"a",kind:"payment",amount:5000}],pairwiseTransfers:[{fromPersonId:"a",toPersonId:"b",amount:300}]}).currentPerson,receivable=build({pairwiseTransfers:[{fromPersonId:"b",toPersonId:"a",amount:200}]}).currentPerson,settled=build().currentPerson;assert.deepEqual([payable.playerPosition,payable.playerNetAmount],["payable",300]);assert.deepEqual([receivable.playerPosition,receivable.playerNetAmount],["receivable",200]);assert.deepEqual([settled.playerPosition,settled.playerNetAmount],["settled",0]);assert.equal(payable.playerPaidAmount,1500);});
test("Person Total 不建立 duplicate Transaction",()=>{const result=build(),person=result.currentPerson;assert.equal(result.transactions.entries.length,2);assert.equal(person.sources.filter(item=>item.transactionId==="meal").length,1);});
test("Person Paid 只採正式 Store Payment、Transaction Payment 與 settled Settlement",()=>{const result=build({memberPayments:[{personId:"a",kind:"payment",amount:1000}]});assert.equal(result.currentPerson.paidAmount,2500);assert.equal(result.currentPerson.pendingAmount,0);assert.equal(result.currentPerson.paidDefinition,"formal_store_payments_plus_transaction_payments_plus_settled_outgoing_settlements");});
test("settled Split 只代表責任狀態，不得直接當成人物實際付款",()=>{const result=build({feePlan:null,transactions:[{transactionId:"drink",type:"expense",title:"飲料",amount:481,paidBy:"payer",splitStatus:"completed",splits:[{personId:"a",amount:99,settlementStatus:"settled"}]}],pairwiseTransfers:[]});assert.equal(result.currentPerson.totalExpense,99);assert.equal(result.currentPerson.paidAmount,0);});
test("同一 Person 在同一 Transaction 的多筆 Split 先聚合成一個帳目摘要",()=>{const result=build({feePlan:null,transactions:[{transactionId:"dinner",type:"expense",title:"晚餐",amount:600,paidBy:"payer",splitStatus:"completed",splits:[{splitId:"s1",personId:"a",amount:166},{splitId:"s2",personId:"a",amount:125}]}]}),sources=result.currentPerson.sources;assert.equal(sources.length,1);assert.equal(sources[0].title,"晚餐");assert.equal(sources[0].amount,291);assert.deepEqual(sources[0].sourceIds,["s1","s2"]);});
test("Prepared View 的正式 Transaction payments 驅動人物已付",()=>{const result=build({feePlan:null,transactions:[],transactionView:{actualExpense:481,splitTotal:1,splitCompleted:1,personSources:[{personId:"a",transactionId:"drink",sourceId:"split-a",title:"飲料",amount:99}],actualPaymentsByPerson:[{personId:"a",amount:200}]}});assert.equal(result.currentPerson.totalExpense,99);assert.equal(result.currentPerson.paidAmount,200);});
test("取消店家付款不計入實付",()=>{const result=build({vendorPayments:[{kind:"payment",amount:3000,status:"cancelled"}]});assert.equal(result.store.actualPaid,0);});
test("分帳完成度不把尚未分帳交易算完成",()=>{const result=build();assert.equal(result.activity.splitTotal,2);assert.equal(result.activity.splitCompleted,1);});
test("同一 Shared Projection 可依 Person 輸出 Car Detail 與 LINE View",()=>{const result=build(),linePerson=result.people.find(item=>item.personId==="a");assert.deepEqual(linePerson,result.currentPerson);});
test("舊 Fee Plan 以正式 memberCharges 相容補回人物劇本費",()=>{const legacyPlan={...plan,playerIds:[],memberCharges:[{personId:"a",amount:1000},{personId:"b",amount:1000}]},person=build({feePlan:legacyPlan}).currentPerson;assert.equal(person.sources.filter(item=>item.sourceType==="store_base_fee").length,1);assert.equal(person.sources.find(item=>item.sourceType==="store_base_fee").amount,1000);});
test("人物待收使用同一 Pairwise Projection 的正式方向",()=>{const person=build({pairwiseTransfers:[{fromPersonId:"b",toPersonId:"a",amount:300},{fromPersonId:"a",toPersonId:"c",amount:125}]}).currentPerson;assert.equal(person.payableAmount,125);assert.equal(person.receivableAmount,300);});
test("同名不同 Transaction 在人物費用來源保持兩筆",()=>{const duplicateTitles=[{transactionId:"dinner-1",type:"expense",title:"晚餐",amount:166,splitStatus:"completed",splits:[{personId:"a",amount:166}]},{transactionId:"dinner-2",type:"expense",title:"晚餐",amount:125,splitStatus:"completed",splits:[{personId:"a",amount:125}]}],sources=build({transactions:duplicateTitles}).currentPerson.sources.filter(item=>item.title==="晚餐");assert.deepEqual(sources.map(item=>[item.transactionId,item.amount]),[["dinner-1",166],["dinner-2",125]]);});
test("逐筆 Split 修改後人物明細由同一來源同步重算",()=>{const before=build({feePlan:null,transactions:[{transactionId:"drink",type:"expense",title:"飲料",amount:481,splitStatus:"completed",splits:[{personId:"a",amount:99}]}]}).currentPerson,after=build({feePlan:null,transactions:[{transactionId:"drink",type:"expense",title:"飲料",amount:481,splitStatus:"completed",splits:[{personId:"a",amount:89}]}]}).currentPerson;assert.equal(before.sources[0].amount,99);assert.equal(before.totalExpense,99);assert.equal(after.sources[0].amount,89);assert.equal(after.totalExpense,89);});
test("Production 等價 identity 關係會先彙整人物帳目，且已付只讀正式金流",()=>{
  const owner="86369a39-4fec-46ad-9afc-a60558dc8a9c",legacyPlayer="f89pkJbkmFLu4ZOw2fXh";
  const result=view.build({
    currentPersonId:owner,
    personIds:[owner,legacyPlayer],
    personIdentityGroups:[{personId:legacyPlayer,identityIds:[legacyPlayer,owner]}],
    feePlan:{playerFee:1000,requiredPlayerCount:6,vendorBaseAmount:6000,memberCharges:[{personId:legacyPlayer,amount:1000}],feeItems:[{feeItemId:"specified-1",title:"指定費",amount:66,allocations:[{personId:legacyPlayer,amount:66}]},{feeItemId:"specified-2",title:"指定費",amount:67,allocations:[{personId:legacyPlayer,amount:67}]}]},
    memberPayments:[{personId:legacyPlayer,kind:"payment",amount:1000},{personId:legacyPlayer,kind:"payment",amount:1000}],
    transactions:[
      {transactionId:"dinner-1",type:"expense",title:"晚餐",amount:500,paidBy:owner,splitStatus:"completed",splits:[{splitId:"d1-owner",personId:owner,amount:166,settlementStatus:"settled"}]},
      {transactionId:"dinner-2",type:"expense",title:"晚餐",amount:500,paidBy:owner,splitStatus:"completed",splits:[{splitId:"d2-owner",personId:owner,amount:125,settlementStatus:"settled"},{splitId:"d2-legacy",personId:legacyPlayer,amount:125,settlementStatus:"payment_due"}]},
      {transactionId:"drink",type:"expense",title:"飲料",amount:350,paidBy:"other",splitStatus:"completed",splits:[{splitId:"drink-owner",personId:owner,amount:87,settlementStatus:"payment_due"},{splitId:"drink-legacy",personId:legacyPlayer,amount:87,settlementStatus:"payment_due"}]}
    ],
    settledPaidByPerson:[{personId:owner,amount:87}],
    pairwiseTransfers:[{fromPersonId:legacyPlayer,toPersonId:"other",amount:87},{fromPersonId:"other",toPersonId:owner,amount:50}]
  });
  assert.equal(result.people.length,1);
  assert.deepEqual(result.currentPerson.sources.filter(item=>item.sourceType==="transaction_split").map(item=>[item.transactionId,item.title,item.amount]),[["dinner-1","晚餐",166],["dinner-2","晚餐",250],["drink","飲料",174]]);
  assert.equal(result.currentPerson.totalExpense,1723);
  assert.equal(result.currentPerson.paidAmount,3087);
  assert.equal(result.currentPerson.pendingAmount,87);
  assert.equal(result.currentPerson.receivableAmount,50);
});
