(function(){"use strict";
const db=window.db||firebase.firestore(),works=db.collection("workScheduleWorks"),V=window.JLYWorkScheduleReadView,B=window.JLYScriptWorkBridge,C=window.JLYStudioScriptCatalog,$=id=>document.getElementById(id),txt=v=>String(v==null?"":v).trim();
let rows=[];
function status(v){$("status").textContent=v;}
function roleMeta(w){const roles=Array.isArray(w.roles)?w.roles:[],people=new Set(roles.flatMap(r=>r.eligiblePersonIds||r.personIds||[]));return roles.length+" 個角色 · "+people.size+" 位可接戲人員";}
function render(){const host=$("scriptList");host.replaceChildren();if(!rows.length){status("尚未建立劇本。");return}status("共 "+rows.length+" 個劇本");rows.forEach(w=>{const row=document.createElement("article");row.className="script-row";const info=document.createElement("div"),name=document.createElement("strong"),meta=document.createElement("small"),actions=document.createElement("div"),edit=document.createElement("button"),schedule=document.createElement("button");name.textContent=w.name||w.workName||"未命名劇本";meta.textContent=roleMeta(w);info.append(name,meta);actions.className="script-actions";edit.type=schedule.type="button";edit.textContent="編輯";schedule.textContent="排班／演員資格";schedule.className="gray";edit.onclick=()=>openEditor(w);schedule.onclick=()=>location.href="work-schedule.html?workId="+encodeURIComponent(w.id);actions.append(edit,schedule);row.append(info,actions);host.append(row);});}
async function load(){if(!V)throw new Error("Work Schedule Prepared View 尚未載入");rows=await V.loadWorkIndex();render();}
async function readExact(id){const snap=await works.doc(id).get();return snap.exists?{id:snap.id,...snap.data()}:null;}
function set(id,v){$(id).value=v==null?"":v;}
async function openEditor(summary){let w=summary;if(summary&&summary.id)w=await readExact(summary.id)||summary;const normalized=B.fromWork(w||{}),booking=C.normalizeStudioScript(w||{}).booking;set("scriptId",w?.id||"");set("name",normalized.name);set("coverUrl",normalized.coverUrl);set("summary",normalized.summary);set("tags",normalized.tags.join(", "));set("playerCount",normalized.playerCount||"");set("durationMinutes",normalized.durationMinutes||"");set("maleSlots",normalized.maleSlots||"");set("femaleSlots",normalized.femaleSlots||"");$("bookingEnabled").checked=booking.enabled;$("allowHostRequest").checked=booking.allowHostRequest;$("depositRequired").checked=booking.depositRequired;set("depositType",booking.depositType);set("depositAmount",booking.depositAmount||"");$("editorTitle").textContent=w?.id?"編輯劇本":"新增劇本";$("listCard").hidden=true;$("editorCard").hidden=false;}
function closeEditor(){$("editorCard").hidden=true;$("listCard").hidden=false;}
async function save(e){e.preventDefault();const existingId=txt($("scriptId").value),existing=existingId?await readExact(existingId):null,ref=existingId?works.doc(existingId):works.doc(),base=existing||{id:ref.id,roles:[]};const script={scriptId:ref.id,name:txt($("name").value),coverUrl:txt($("coverUrl").value),summary:txt($("summary").value),tags:txt($("tags").value).split(/[,，]/).map(txt).filter(Boolean),playerCount:Number($("playerCount").value||0),durationMinutes:Number($("durationMinutes").value||0),maleSlots:Number($("maleSlots").value||0),femaleSlots:Number($("femaleSlots").value||0)};const merged=B.mergeScriptIntoWork(base,script),booking={enabled:$("bookingEnabled").checked,allowHostRequest:$("allowHostRequest").checked,hostRequestMode:"preference",depositRequired:$("depositRequired").checked,depositType:$("depositType").value,depositAmount:Math.max(0,Number($("depositAmount").value||0))};const now=firebase.firestore.FieldValue.serverTimestamp(),payload={scriptId:ref.id,name:merged.name,studioName:merged.studioName||"凱崴私團",coverUrl:merged.coverUrl,summary:merged.summary,tags:merged.tags,playerCount:merged.playerCount,maleSlots:merged.maleSlots,femaleSlots:merged.femaleSlots,durationMinutes:merged.durationMinutes,roles:merged.roles||[],booking,updatedAt:now};if(!existing)payload.createdAt=now;await ref.set(payload,{merge:true});await V.updateWork({id:ref.id,...payload,updatedAt:new Date().toISOString()});rows=await V.loadWorkIndex();render();closeEditor();alert("劇本設定已儲存。既有排班與可接戲演員資格已保留。");}
$("createScript").onclick=()=>openEditor(null);$("closeEditor").onclick=closeEditor;$("scriptForm").onsubmit=save;load().catch(e=>{console.error(e);status("劇本讀取失敗："+(e.message||e));});
})();