const fs=require('fs'),assert=require('assert');
const vote=fs.readFileSync('js/modules/work-schedule/studio-matching-vote.js','utf8'),page=fs.readFileSync('pages/studio-matching-vote.html','utf8'),ws=fs.readFileSync('js/modules/work-schedule/studio-matching-workspace.js','utf8'),composer=fs.readFileSync('js/modules/work-schedule/work-schedule-session-composer.js','utf8'),api=fs.readFileSync('api/studio-matching-vote-context.js','utf8'),loginState=fs.readFileSync('api/line-login-state.js','utf8');
assert(!page.includes('voteName'));
assert(page.includes('/js/line.js?v=3'));
assert(vote.includes('JLYLineLogin.start'));
assert(vote.includes("purpose:'studio_matching_vote'"));
assert(vote.includes('/api/studio-matching-vote-context'));
assert(page.includes('studio-vote-slot'));
assert(api.includes('formal_person_required'));
assert(api.includes('studio_membership_required'));
assert(api.includes('personId:person.id'));
assert(loginState.includes('"studio_matching_vote"'));
assert(ws.includes('hostName'));
assert(ws.includes('draft.hostName'));
assert(composer.includes("sessionHosts[hostKey(draft.date,0)]=txt(draft.hostName||'')"));
assert(composer.includes('matchingAllowedPersonIds'));
console.log('studio matching LINE host handoff ok');
