const fs=require('fs'),vm=require('vm'),assert=require('assert');
const policyCode=fs.readFileSync('js/modules/work-schedule/work-schedule-change-policy.js','utf8');
const lifecycleCode=fs.readFileSync('js/modules/work-schedule/work-schedule-lifecycle.js','utf8');
let seq=0;const eventWrites=[];
const db={collection:name=>({doc:()=>({id:`${name}-${++seq}`})})};
function firestore(){return db}firestore.FieldValue={serverTimestamp:()=>({serverTimestamp:true})};
const firebase={firestore},window={db};
const context={window,firebase,console,Date};vm.runInNewContext(policyCode,context);window.JLYWorkScheduleChangePolicy=window.JLYWorkScheduleChangePolicy;vm.runInNewContext(lifecycleCode,context);const L=window.JLYWorkScheduleLifecycle;
assert.ok(L,'lifecycle should load');
const candidate={id:'s-new',workId:'w1',studioId:'A',date:'2026-10-01',startTime:'19:00',endTime:'23:00',assignedPersonIds:['p1']};
const sameStudio={id:'s-a',workId:'w2',studioId:'A',date:'2026-10-01',startTime:'20:00',endTime:'22:00',assignedPersonIds:['p1'],workName:'A店本'};
const otherStudio={id:'s-b',workId:'w3',studioId:'B',date:'2026-10-01',startTime:'18:00',endTime:'20:00',assignedPersonIds:['p1'],workName:'B店本'};
let conflicts=L.findConflicts({personIds:['p1'],candidate,rows:[sameStudio,otherStudio]});
assert.equal(conflicts.length,2);assert.equal(conflicts[0].disclosure,'same-studio-detail');assert.equal(conflicts[1].disclosure,'busy-only');
const sameWorkNoStudio={id:'s-c',workId:'w1',date:'2026-10-01',startTime:'21:00',endTime:'22:00',assignedPersonIds:['p1'],workName:'同一本'};
conflicts=L.findConflicts({personIds:['p1'],candidate:{...candidate,studioId:''},rows:[sameWorkNoStudio]});assert.equal(conflicts[0].disclosure,'same-studio-detail');
const dutyBefore={id:'s1',workId:'w1',date:'2026-10-01',startTime:'19:00',endTime:'23:00',assignedPersonIds:['p1'],staffSlots:[{id:'x',label:'1',personId:'p1'}]};
const dutyAfter={...dutyBefore,staffSlots:[{id:'x',label:'主控',personId:'p1'}]};let summary=L.summarize(dutyBefore,dutyAfter);assert.equal(summary.calendarPlan.create.length+summary.calendarPlan.update.length+summary.calendarPlan.remove.length,0);assert.equal(summary.notificationPlan[0].type,'duty_changed');
const assignmentAfter={...dutyBefore,assignedPersonIds:['p2'],personIds:['p2'],people:[{personId:'p2',name:'小白'}],staffSlots:[{id:'x',label:'1',personId:'p2'}]};summary=L.summarize(dutyBefore,assignmentAfter);assert.deepEqual([...summary.calendarPlan.create],['p2']);assert.deepEqual([...summary.calendarPlan.remove],['p1']);
const batch={set:(ref,data)=>eventWrites.push({ref,data})};L.appendToBatch(batch,{id:'s1'},dutyBefore,assignmentAfter,{source:'test',conflictAcknowledged:true,conflictCount:2});assert.equal(eventWrites.length,1);assert.equal(eventWrites[0].data.notificationStatus,'pending');assert.equal(eventWrites[0].data.personalCalendarStatus,'waiting_person_calendar');assert.equal(eventWrites[0].data.conflictAcknowledged,true);assert.equal(eventWrites[0].data.conflictCount,2);
const privateMessage=L.conflictMessage([{personId:'p1',row:otherStudio,disclosure:'busy-only'}],{personLabel:()=> '詩婕'});assert.ok(privateMessage.includes('其他安排'));assert.ok(!privateMessage.includes('B店本'));
console.log('work-schedule-lifecycle ok');
