const fs=require('fs');const assert=require('assert');
const page=fs.readFileSync('pages/work-schedule.html','utf8');
const js=fs.readFileSync('js/modules/work-schedule/work-schedule-session-composer.js','utf8');
const css=fs.readFileSync('css/pages/work-schedule-session-composer.css','utf8');
assert(page.includes('work-schedule-session-composer.css?v=1'));
assert(page.includes('work-schedule-session-composer.js?v=1'));
assert(!page.includes('work-schedule-multi-date.js?v=2'));
assert(js.includes('selectedDates=new Set'));
assert(js.includes("timeSlots=[{start:'11:00',end:'18:00'}]"));
assert(js.includes("timeSlots.push({start:'19:00',end:'02:00'})"));
assert(js.includes('每場直接排人'));
assert(js.includes('建立全部排班'));
assert(js.includes("endDate:endDate(date,start,end)"));
assert(js.includes('跨日班只顯示在開始日期'));
assert(js.includes('assignedPersonIds:ids'));
assert(js.includes('work_schedule_session_composer'));
assert(css.includes('.session-composer-person-chips'));
assert(css.includes('border-radius:999px'));
console.log('work schedule session composer regression passed');
