const fs=require('fs'),assert=require('assert');
const page=fs.readFileSync('pages/work-schedule.html','utf8');
const js=fs.readFileSync('js/modules/work-schedule/work-schedule-date-search.js','utf8');
const css=fs.readFileSync('css/pages/work-schedule-date-search.css','utf8');
const view=fs.readFileSync('js/modules/work-schedule/work-schedule-read-view.js','utf8');
assert(!page.includes('近期班表'),'legacy upcoming block should be removed');
assert(!page.includes('指定月份'),'month browser label should be removed');
assert(page.includes('id="scheduleDateSearch"'),'date search form should exist');
assert(page.indexOf('id="scheduleDateSearch"')<page.indexOf('id="scheduleDashboard"'),'controls must stay above schedule results');
assert(js.includes("p.length===2"),'M/D shorthand should be supported');
assert(js.includes('explicitYear'),'M/D and Y/M/D modes should be distinct');
assert(js.includes("p.length===3"),'explicit year/M/D should be supported');
assert(js.includes('loadMonthIndex'),'M/D search should use lightweight month index across years');
assert(js.includes("endsWith(`-${parsed.monthText}`)"),'M/D should search matching month views across all indexed years');
assert(js.includes("slice(5)===`${parsed.monthText}-${parsed.dayText}`"),'M/D should match the same month/day across years');
assert(js.includes("clear.textContent='×'"),'clear action should be a compact x');
assert(js.includes('clear.hidden=!input.value'),'clear x should only appear when input has text');
assert(js.includes('async function loadDefault()'),'default results should not depend on hidden current-month dashboard state');
assert(js.includes("filter(k=>String(k)>=currentMonth).slice(0,3)"),'default results should use a bounded View-first future window');
assert(css.includes('.schedule-results-head{display:none!important}'),'redundant schedule heading must be visually removed');
assert(css.includes('#scheduleDateClear[hidden]'),'compact clear x must support hidden state');
assert(view.includes("views.doc('month-index')"),'read model should maintain a lightweight month index');
assert(view.includes("where('type','==','work-schedule-month')"),'month index fallback must inspect view docs only');
assert(!js.includes('workShifts'),'date search must not scan authoritative shifts');
assert(!js.includes('location.reload'),'date search must not reload the page');
console.log('work-schedule-date-search.test.js passed');
