/* JLY Host System V3 - canonical Person search for Car Detail manual add */
console.log("player-search.js V2 已成功載入！");
(function(){"use strict";
let approvedSameNameIds=[];
function nowTime(){return new Date().toISOString();}function text(v){return String(v==null?"":v).trim();}function normalizePlayerName(v){return text(v).toLowerCase().replace(/\s+/g,"");}
function getPlayerDatabaseName(p){p=p&&typeof p==="object"?p:{};return p.displayName||p.nickname||p.playerName||p.lineDisplayName||p.name||"未命名人員";}
function getSearchableNames(p){p=p&&typeof p==="object"?p:{};return[p.displayName,p.nickname,p.playerName,p.name,p.lineDisplayName,...(Array.isArray(p.aliases)?p.aliases:[])].map(normalizePlayerName).filter(Boolean);}
function moduleData(){return window.JLYMemberPickerData||null;}
async function loadCanonicalPeople(){const d=moduleData();if(d&&typeof d.loadPersonDirectory==="function")return d.loadPersonDirectory();if(!window.db)throw new Error("Firebase 尚未載入");const snap=await window.db.collection("players").get();const rows=snap.docs.map(doc=>({id:doc.id,...doc.data()}));return d&&typeof d.dedupeCanonicalMembers==="function"?d.dedupeCanonicalMembers(rows):rows;}
async function searchPlayersByName(name){const target=normalizePlayerName(name);if(!target)return[];const people=await loadCanonicalPeople();return people.filter(p=>getSearchableNames(p).some(n=>n===target));}
function buildGuestPlayerData(name,id){const clean=text(name),now=nowTime();return{id:id||"",displayName:clean,nickname:clean,playerName:clean,aliases:clean?[clean]:[],normalizedName:normalizePlayerName(clean),memberType:"guest",type:"guest",identityStatus:"guest",status:"active",isLineLinked:false,lineUserId:null,lineDisplayName:"",linePictureUrl:"",defaultPosition:"不限",defaultCrossPlay:false,playCount:0,source:"host_manual",createdAt:now,updatedAt:now};}
async function createGuestPlayer(name){if(!window.db)throw new Error("Firebase 尚未載入");const clean=text(name);if(!clean)throw new Error("玩家名稱不可空白");const matches=await searchPlayersByName(clean);const ids=matches.map(p=>text(p.id)).filter(Boolean).sort();const approved=approvedSameNameIds.slice().sort();const sameApproved=ids.length>0&&ids.length===approved.length&&ids.every((id,i)=>id===approved[i]);approvedSameNameIds=[];if(matches.length&&!sameApproved){const e=new Error("找到同名 Person，必須先明確選擇既有人員或確認建立另一位真人。");e.code="same_name_person_requires_resolution";e.sameNameCandidates=matches;throw e;}const ref=window.db.collection("players").doc();const row=buildGuestPlayerData(clean,ref.id);if(matches.length){row.sameNameOverride=true;row.sameNameReferenceIds=ids;row.source="host_manual_same_name_override";}await ref.set(row,{merge:true});return row;}
function getIdentityLabel(p){const d=moduleData();if(d&&typeof d.getIdentityLabel==="function")return d.getIdentityLabel(p);return p&&(p.isLineLinked===true||text(p.lineUserId))?"已連結 LINE":"尚未連結";}
function buildPlayerSelectionMessage(matches){let msg="找到以下既有人員：\n\n";matches.forEach((p,i)=>{msg+=`${i+1}. ${getPlayerDatabaseName(p)}／${getIdentityLabel(p)}／${p.defaultPosition||"不限"}${p.defaultCrossPlay===true?"／反串":""}／歷史 ${Number(p.playCount||0)} 場\n`;});return msg+"\n請輸入人員前面的編號。\n輸入 0 代表這是另一位不同的真人。";}
function selectPlayerFromMatches(matches){const rows=Array.isArray(matches)?matches:[];approvedSameNameIds=[];if(!rows.length)return{cancelled:false,selectedPlayer:null,createNew:true};const input=prompt(buildPlayerSelectionMessage(rows),"1");if(input===null)return{cancelled:true,selectedPlayer:null,createNew:false};const n=Number(String(input).trim());if(!Number.isInteger(n)||n<0||n>rows.length){alert("輸入的編號不正確");return{cancelled:true,selectedPlayer:null,createNew:false};}if(n===0){approvedSameNameIds=rows.map(p=>text(p.id)).filter(Boolean);return{cancelled:false,selectedPlayer:null,createNew:true};}return{cancelled:false,selectedPlayer:rows[n-1],createNew:false};}
async function selectOrCreatePlayer(name){const clean=text(name);if(!clean)return null;const matches=await searchPlayersByName(clean);const choice=selectPlayerFromMatches(matches);if(choice.cancelled)return null;if(choice.selectedPlayer)return choice.selectedPlayer;const ok=confirm(matches.length?`確定「${clean}」是另一位不同的真人，要建立新的 Person 嗎？`:`目前沒有人員「${clean}」，是否建立為新的 Person？`);if(!ok){approvedSameNameIds=[];return null;}return createGuestPlayer(clean);}
window.JLYCarDetailPlayerSearch={normalizePlayerName,getPlayerDatabaseName,getSearchableNames,loadCanonicalPeople,searchPlayersByName,buildGuestPlayerData,createGuestPlayer,getIdentityLabel,buildPlayerSelectionMessage,selectPlayerFromMatches,selectOrCreatePlayer};console.log("✅ Car Detail Player Search V2 已載入");
})();