"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const {buildGoogleCalendarPrefillUrl}=require("../../services/line/google-calendar-prefill-url");
const {buildMemberWelcomeCard}=require("../../services/line/member-welcome-card");
const car={scriptName:"孤注 & 花火",gameDate:"2027-10-04",gameTime:"19:30",calendar:{eventDurationMinutes:180},studioName:"小巷劇本館",locationName:"台北市中山區",publicNote:"請提前抵達"};
function params(value){const uri=buildGoogleCalendarPrefillUrl(value);assert.ok(uri);const parsed=new URL(uri);assert.equal(parsed.hostname,"calendar.google.com");assert.equal(parsed.pathname,"/calendar/r/eventedit");return parsed.searchParams;}
test("personal Google event has Taiwan local date converted to UTC",()=>{const p=params(car);assert.equal(p.get("dates"),"20271004T113000Z/20271004T143000Z");assert.equal(p.get("stz"),"Asia/Taipei");assert.equal(p.get("etz"),"Asia/Taipei");assert.equal(p.get("text"),"劇本－孤注 & 花火");assert.equal(p.get("location"),"小巷劇本館｜台北市中山區");});
test("cross-midnight duration and explicit next-day end are exact",()=>{assert.equal(params({scriptName:"夜場",gameDate:"2027-10-04",gameTime:"23:00",durationMinutes:480}).get("dates"),"20271004T150000Z/20271004T230000Z");assert.equal(params({scriptName:"夜場",gameDate:"2027-10-04",gameTime:"20:00",endDate:"2027-10-05",endTime:"01:30"}).get("dates"),"20271004T120000Z/20271004T173000Z");});
test("missing or incorrect schedule never creates a Google URL",()=>{for(const invalid of [null,{}, {...car,gameDate:""}, {...car,gameTime:""}, {...car,gameDate:"2027-02-29"},{...car,gameTime:"24:00"},{...car,calendar:{}},{...car,endTime:"17:00"}])assert.equal(buildGoogleCalendarPrefillUrl(invalid),null);});
test("LINE URI stays below maximum length",()=>{const uri=buildGoogleCalendarPrefillUrl({...car,publicNote:"極".repeat(1000)});assert.ok(uri);assert.ok(uri.length<=1000);});
test("existing DM and player entries remain, third action goes directly to Google",()=>{const c=buildMemberWelcomeCard({...car,id:"car id/1"},{baseUrl:"https://example.com/"});const buttons=c.contents.body.contents;assert.deepEqual(buttons.map(x=>x.action&&x.action.label),["🎭 我是本場 DM","🎮 我要報名玩家","📅 加入我的 Google 行事曆"]);assert.equal(buttons[0].action.uri,"https://example.com/pages/car-view.html?id=car%20id%2F1&entry=dm&source=line_group");assert.equal(buttons[1].action.uri,"https://example.com/pages/car-view.html?id=car%20id%2F1&entry=player&source=line_group");assert.equal(new URL(buttons[2].action.uri).hostname,"calendar.google.com");});
test("late car metadata offers safe calendar placeholder, not guessed event",()=>{const c=buildMemberWelcomeCard(null,{baseUrl:"https://example.com",carId:"car-1"});assert.equal(c.contents.body.contents.filter(x=>x.action).length,2);assert.match(c.contents.body.contents[2].text,/暫時無法新增行程/);});
