"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const { isCarExpired, markMembershipChanged, initializeMembershipSnapshot, verifyMembershipSnapshot } = require("../../services/line/group-membership-health-service");
const { processMembershipEvent } = require("../../services/line/group-membership-event-service");
const NOW = "2026-09-03T01:00:00.000Z";
function memoryDependencies(seed = null) { let snapshot=seed,action=null; return { now:()=>NOW,currentDate:()=>new Date(NOW),getSnapshot:async()=>snapshot,saveSnapshot:async(_g,patch)=>{snapshot={...(snapshot||{}),...patch};return snapshot;},savePendingAction:async(_c,next)=>{action=next;return next;},completePendingAction:async()=>{action={...(action||{}),status:"completed"};},inspect:()=>({snapshot,action}) }; }

test("expired or ended cars are skipped before LINE membership work", async()=>{assert.equal(isCarExpired({status:"ended",date:"2026-09-10"},new Date(NOW)),true);assert.equal(isCarExpired({status:"active",date:"2026-09-02"},new Date(NOW)),true);const deps=memoryDependencies();let countCalls=0;const result=await initializeMembershipSnapshot({groupId:"G1",carId:"C1",car:{status:"ended",ownerId:"P1"}},{...deps,getGroupMemberCount:async()=>{countCalls+=1;return 8;}});assert.equal(result.reason,"car_expired");assert.equal(countCalls,0);});

test("first binding initializes only that group and creates review action",async()=>{const deps=memoryDependencies();const result=await initializeMembershipSnapshot({groupId:"G1",carId:"C1",car:{status:"active",date:"2026-09-10",ownerId:"P1"}},{...deps,getGroupMemberCount:async g=>{assert.equal(g,"G1");return 8;},listGroupMemberIds:async()=>["U1","U2"]});assert.equal(result.initialized,true);const s=deps.inspect();assert.equal(s.snapshot.status,"needs_review");assert.equal(s.snapshot.lineMemberCount,8);assert.deepEqual(s.snapshot.lineUserIds,["U1","U2"]);assert.equal(s.snapshot.lineMemberIdsStatus,"available");assert.equal(s.action.actionType,"line_membership_review");assert.match(s.action.targetUrl,/carId=C1/);});

test("member ID permission failure still initializes from LINE group count",async()=>{const deps=memoryDependencies();const result=await initializeMembershipSnapshot({groupId:"G1",carId:"C1",car:{status:"active",date:"2026-09-10",ownerId:"P1"}},{...deps,getGroupMemberCount:async()=>8,listGroupMemberIds:async()=>{throw new Error("line_group_membership_failed_403");}});assert.equal(result.initialized,true);assert.equal(result.reason,"snapshot_initialized_count_only");const s=deps.inspect();assert.equal(s.snapshot.status,"needs_review");assert.equal(s.snapshot.lineMemberCount,8);assert.deepEqual(s.snapshot.lineUserIds,[]);assert.equal(s.snapshot.lineMemberIdsStatus,"unavailable");assert.equal(s.action.actionType,"line_membership_review");});

test("host verification accepts current reality as baseline even when player and LINE counts differ",async()=>{const deps=memoryDependencies({carId:"C1",status:"needs_review",membershipRevision:7,lineMemberCount:7,pendingJoinedUserIds:[],pendingLeftUserIds:[]});const result=await verifyMembershipSnapshot({groupId:"G1",carId:"C1",verifiedBy:"P1",playerCount:6},deps);assert.equal(result.verified,true);const s=deps.inspect();assert.equal(s.snapshot.status,"verified");assert.equal(s.snapshot.verifiedLineMemberCount,7);assert.equal(s.snapshot.verifiedPlayerCount,6);assert.equal(s.snapshot.verifiedMembershipRevision,7);assert.deepEqual(s.snapshot.pendingJoinedUserIds,[]);assert.deepEqual(s.snapshot.pendingLeftUserIds,[]);assert.equal(s.action.status,"completed");});

test("join and leave invalidate verified snapshot even when net count is unchanged",async()=>{const deps=memoryDependencies({carId:"C1",status:"verified",membershipRevision:7,lineMemberCount:8,verifiedAt:"2026-09-01T00:00:00.000Z",verifiedLineMemberCount:8,verifiedPlayerCount:6});await markMembershipChanged({eventType:"memberJoined",groupId:"G1",carId:"C1",car:{status:"active",date:"2026-09-10",ownerId:"P1"},joinedMembers:[{userId:"U_NEW"}]},deps);await markMembershipChanged({eventType:"memberLeft",groupId:"G1",carId:"C1",car:{status:"active",date:"2026-09-10",ownerId:"P1"},leftMembers:[{userId:"U_OLD"}]},deps);const s=deps.inspect();assert.equal(s.snapshot.status,"needs_review");assert.deepEqual(s.snapshot.pendingJoinedUserIds,["U_NEW"]);assert.deepEqual(s.snapshot.pendingLeftUserIds,["U_OLD"]);assert.equal(s.snapshot.membershipRevision,9);assert.equal(s.snapshot.verifiedPlayerCount,6);});

test("webhook processor touches only the event group binding",async()=>{const calls=[];const result=await processMembershipEvent({type:"memberJoined",source:{type:"group",groupId:"G_A"},joined:{members:[{type:"user",userId:"U9"}]}},{resolveGroupBinding:async g=>{calls.push(["binding",g]);return{bound:true,binding:{carId:"C_A"}};},getCarById:async c=>{calls.push(["car",c]);return{id:c,ownerId:"P1",status:"active",date:"2026-09-10"};},markMembershipChanged:async input=>{calls.push(["mark",input.groupId,input.carId,input.joinedMembers[0].userId]);return{changed:true,reason:"membership_changed"};}});assert.equal(result.handled,true);assert.deepEqual(calls,[["binding","G_A"],["car","C_A"],["mark","G_A","C_A","U9"]]);});