(function () {
  "use strict";
  const escape = value => String(value == null ? "" : value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const money = value => `$${Number(value || 0).toLocaleString("zh-TW")}`;
  function buildShellHtml() {
    return `<section class="card accounting-card" id="accountingSection"><div class="accounting-heading"><div><h3>💰 車團帳務</h3><p>正在載入帳務資料…</p></div></div></section>`;
  }
  function statusLabel(transaction) {
    if (transaction.splitStatus === "pending") return "🟡 待分帳";
    if ((transaction.splits || []).length && transaction.splits.every(split => split.settlementStatus === "settled")) return "🟢 全部結清";
    return "🔵 已分帳／待付款";
  }
  function settlementRows(item, model) {
    if (item.splitStatus === "pending") return "";
    return (item.splits || []).filter(split=>split.settlementStatus!=="settled"&&(split.personId===model.viewPersonId||item.paidBy===model.viewPersonId)).map(split => {
      const mine=split.personId===model.currentPersonId,receiver=item.paidBy===model.currentPersonId,targetMember=model.membersById.get(split.personId),receiverMember=model.membersById.get(item.paidBy),canManage=model.managementMode&&model.isManager&&targetMember&&!targetMember.usesSystem,canConfirmForReceiver=model.managementMode&&model.isManager&&model.viewPersonId===item.paidBy&&receiverMember&&!receiverMember.usesSystem,name=model.memberNames.get(split.personId)||split.displayName||"成員";
      let label="尚未付款",buttons="";
      if(split.settlementStatus==="settled")label="已結清";
      else if(split.settlementStatus==="payment_claimed"){label="已付款，待確認";if(canConfirmForReceiver)buttons=`<button data-action="confirm" data-target-person-id="${escape(item.paidBy)}">代為確認收款</button>`;else{if(mine)buttons=`<button data-action="withdraw">撤回</button>`;if(receiver)buttons+=`<button data-action="confirm">確認收款</button>`;else if(canManage)buttons+=`<button data-action="confirm">代為確認</button>`;}}
      else if(split.settlementStatus==="settlement_rejected")label="付款被退回";
      if(["payment_due","settlement_rejected"].includes(split.settlementStatus)){
        if(mine)buttons+=`<button data-action="claim">已付款</button>`;
        if(receiver)buttons+=`<button data-action="receiver_settle">已收款</button>`;
        else if(canManage)buttons+=`<button data-action="manager_claim">代為登記付款</button>`;
      }
      return `<div class="accounting-settlement-row" data-transaction-id="${escape(item.transactionId)}" data-split-id="${escape(split.splitId)}"><span>${escape(name)}｜${money(split.amount)}｜${label}</span><div>${buttons}</div></div>`;
    }).join("");
  }
  function buildDashboardHtmlLegacy(model) {
    const netSettlement = netSettlementHtml(model);
    const counts = model.counts, members = model.members || [];
    const recent = netSettlement + ((model.transactions || []).map((item,index) => `<article class="accounting-entry" data-transaction-id="${escape(item.transactionId)}" data-filter-state="${escape(model.getFilterState(item))}"${index>=5?" hidden":""}><div class="accounting-entry-summary"><div><strong>${escape(item.title || item.description || "未命名帳目")}</strong><small>付款人：${escape(model.memberNames.get(item.paidBy || item.payerMemberId) || item.payerDisplayName || "待確認")}</small></div><div><b>${money(item.amount)}</b><span>${statusLabel(item)}</span>${item.splitStatus==="pending"?`<button type="button" class="accounting-split-open" data-transaction-id="${escape(item.transactionId)}">分帳</button>`:""}</div></div><div class="accounting-settlement-list">${settlementRows(item,model)}</div></article>`).join("") || `<p class="empty-text">目前沒有帳目</p>`);
    const options = members.map(member => `<option value="${escape(member.personId)}"${member.personId===model.currentPersonId?" selected":""}>${escape(member.displayName)}</option>`).join("");
    return `<div class="accounting-heading"><div><h3>💰 車團帳務</h3><p>待處理 ${counts.total}</p></div><button type="button" id="accountingQuickOpen">＋ 快速記帳</button></div><div class="accounting-pending-grid"><span>待分帳 <b>${counts.pendingSplit}</b></span><span>待付款 <b>${counts.paymentDue}</b></span><span>待確認收款 <b>${counts.paymentConfirmation}</b></span></div><form id="accountingQuickForm" class="accounting-quick-form" hidden><h4>快速記帳</h4><label>項目<input id="accountingTitle" maxlength="80" required placeholder="例如：晚餐"></label><label>金額<input id="accountingAmount" type="number" min="1" step="1" inputmode="numeric" required></label><label>付款人<select id="accountingPaidBy" required>${options}</select></label><p id="accountingFormStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSave">記下來</button><button type="button" id="accountingCancel">取消</button></div></form><form id="accountingSplitForm" class="accounting-quick-form" hidden><h4 id="accountingSplitTitle">分帳</h4><input type="hidden" id="accountingSplitTransactionId"><label>分帳方式<select id="accountingSplitMode"><option value="equal">平均分帳</option><option value="custom">自訂金額</option></select></label><div class="accounting-member-heading"><span>參與成員</span><button type="button" id="accountingSelectAll" class="accounting-select-all">取消全選</button></div><fieldset class="accounting-member-list">${members.map(member=>`<label><input type="checkbox" name="splitMember" value="${escape(member.personId)}" checked><span>${escape(member.displayName)}</span><input class="accounting-custom-amount" data-person-id="${escape(member.personId)}" type="number" min="0" step="1" inputmode="numeric" hidden></label>`).join("")}</fieldset><p id="accountingSplitStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSplitSave">完成分帳</button><button type="button" id="accountingSplitCancel">取消</button></div></form><div class="accounting-list-heading"><h4 id="accountingListTitle">${model.detailMode?"詳細帳目":"最近帳目"}</h4><button type="button" id="accountingViewAll" class="accounting-view-all">${model.detailMode?"篩選本頁":"查看詳細帳務"}</button></div><nav id="accountingFilters" class="accounting-filters" hidden><button data-filter="all">全部</button><button data-filter="pending">待處理</button><button data-filter="pending_split">待分帳</button><button data-filter="payment_due">待付款</button><button data-filter="payment_confirmation">待確認</button><button data-filter="settled">已結清</button></nav><div class="accounting-entry-list">${recent}</div>${model.detailMode&&model.detailHasMore?`<button type="button" id="accountingLoadMore" class="accounting-view-all">載入下一頁（10 筆）</button>`:""}<p id="accountingFilterEmpty" class="empty-text" hidden>目前沒有符合條件的帳目</p>`;
  }
  function buildDashboardHtmlBase(model) {
    const members=model.members||[],counts=model.counts||{},options=members.map(member=>`<option value="${escape(member.personId)}"${member.personId===model.currentPersonId?" selected":""}>${escape(member.displayName)}</option>`).join("");
    const managerMenu=model.isManager?`<div class="accounting-manager-menu"><button type="button" id="accountingManageToggle" aria-label="${model.managementMode?"離開帳務管理":"進入帳務管理"}">${model.managementMode?"完成":"⋯"}</button></div>`:"";
    const managerPanel=model.managementMode?`<section class="accounting-management-panel"><strong>管理帳務</strong><label>查看成員視角<select id="accountingViewPerson">${members.map(member=>`<option value="${escape(member.personId)}"${member.personId===model.viewPersonId?" selected":""}>${escape(member.displayName)}${member.usesSystem?"":"（未使用系統）"}</option>`).join("")}</select></label><small>只有未使用系統的成員可由主揪代為處理。</small></section>`:"";
    const rows=(model.transactions||[]).filter(item=>item.splitStatus==="pending"||item.paidBy===model.viewPersonId||(item.splits||[]).some(split=>split.personId===model.viewPersonId)).map((item,index)=>`<article class="accounting-entry" data-transaction-id="${escape(item.transactionId)}" data-filter-state="${escape(model.getFilterState(item))}"${index>=5?" hidden":""}><div class="accounting-entry-summary"><div><strong>${escape(item.title||item.description||"未命名帳目")}</strong><small>付款人：${escape(model.memberNames.get(item.paidBy||item.payerMemberId)||item.payerDisplayName||"待確認")}</small></div><div><b>${money(item.amount)}</b><span>${statusLabel(item)}</span>${item.splitStatus==="pending"?`<button type="button" class="accounting-split-open" data-transaction-id="${escape(item.transactionId)}">分帳</button>`:""}</div></div><div class="accounting-settlement-list">${settlementRows(item,model)}</div></article>`).join("")||`<p class="empty-text">目前沒有與你相關的帳目</p>`;
    return `<div class="accounting-heading"><div><h3>💰 車團帳務</h3><p>${model.managementMode?`正在查看：${escape(model.memberNames.get(model.viewPersonId)||"成員")}`:"我的帳務"}</p></div><div class="accounting-heading-actions"><button type="button" id="accountingQuickOpen">＋ 快速記帳</button>${managerMenu}</div></div>${managerPanel}<div class="accounting-pending-grid"><span>我還要付 <b>${money(model.personalSettlement.payable)}</b></span><span>別人還欠我 <b>${money(model.personalSettlement.receivable)}</b></span><span>等待我確認 <b>${counts.paymentConfirmation||0}</b></span></div><form id="accountingQuickForm" class="accounting-quick-form" hidden><h4>快速記帳</h4><label>項目<input id="accountingTitle" maxlength="80" required></label><label>金額<input id="accountingAmount" type="number" min="1" step="1" required></label><label>付款人<select id="accountingPaidBy" required>${options}</select></label><p id="accountingFormStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSave">記下來</button><button type="button" id="accountingCancel">取消</button></div></form><form id="accountingSplitForm" class="accounting-quick-form" hidden><h4 id="accountingSplitTitle">分帳</h4><input type="hidden" id="accountingSplitTransactionId"><label>分帳方式<select id="accountingSplitMode"><option value="equal">平均分帳</option><option value="custom">自訂金額</option></select></label><div class="accounting-member-heading"><span>參與成員</span><button type="button" id="accountingSelectAll" class="accounting-select-all">取消全選</button></div><fieldset class="accounting-member-list">${members.map(member=>`<label><input type="checkbox" name="splitMember" value="${escape(member.personId)}" checked><span>${escape(member.displayName)}</span><input class="accounting-custom-amount" data-person-id="${escape(member.personId)}" type="number" min="0" step="1" hidden></label>`).join("")}</fieldset><p id="accountingSplitStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSplitSave">完成分帳</button><button type="button" id="accountingSplitCancel">取消</button></div></form>${netSettlementHtml(model)}<div class="accounting-list-heading"><h4 id="accountingListTitle">${model.detailMode?"詳細帳目":"最近帳目"}</h4><button type="button" id="accountingViewAll" class="accounting-view-all">${model.detailMode?"篩選本頁":"查看詳細帳務"}</button></div><nav id="accountingFilters" class="accounting-filters" hidden><button data-filter="all">全部</button><button data-filter="pending">待處理</button><button data-filter="settled">已結清</button></nav><div class="accounting-entry-list">${rows}</div>${model.detailMode&&model.detailHasMore?`<button type="button" id="accountingLoadMore" class="accounting-view-all">載入下一頁（10 筆）</button>`:""}<p id="accountingFilterEmpty" class="empty-text" hidden>目前沒有符合條件的帳目</p>`;
  }
  function netSettlementHtml(model) {
    const transfers = model.personalSettlement && model.personalSettlement.transfers || [];
    const rows = transfers.map(transfer => {
      const from = model.memberNames.get(transfer.fromPersonId) || "待確認成員";
      const to = model.memberNames.get(transfer.toPersonId) || "待確認成員";
      return `<li><strong>${escape(from)}</strong><span>付給</span><strong>${escape(to)}</strong><b>${money(transfer.amount)}</b></li>`;
    }).join("");
    return `<section class="accounting-net-settlement"><div><h4>${model.managementMode?"成員結算結果":"我的結算結果"}</h4><small>已將相關未結清帳目互相抵扣</small></div>${rows?`<ul>${rows}</ul>`:`<p>目前沒有需要付款或收款的金額</p>`}</section>`;
  }
  function netSettlementAction(model,item,claim) {
    const receiver=model.membersById.get(item.toPersonId);
    const managerCanConfirm=claim&&model.managementMode&&model.isManager&&receiver&&!receiver.usesSystem;
    if(managerCanConfirm)return `<button type="button" class="accounting-net-action" data-action="manager_confirm" data-settlement-id="${escape(claim.settlementId)}" data-target-person-id="${escape(claim.toPersonId)}">代為確認收款</button>`;
    if(claim&&model.currentPersonId===claim.fromPersonId)return `<button type="button" class="accounting-net-action" data-action="withdraw" data-settlement-id="${escape(claim.settlementId)}">撤回付款</button>`;
    if(claim&&model.currentPersonId===claim.toPersonId)return `<button type="button" class="accounting-net-action" data-action="confirm" data-settlement-id="${escape(claim.settlementId)}">確認收款</button>`;
    if(!claim&&item.fromPersonId===model.viewPersonId&&model.currentPersonId===item.fromPersonId)return `<button type="button" class="accounting-net-action" data-action="claim" data-from-person-id="${escape(item.fromPersonId)}" data-to-person-id="${escape(item.toPersonId)}" data-amount="${item.amount}">我已付款</button>`;
    return "";
  }
  function settlementDialogRows(model,type) {
    const personId=model.viewPersonId;if(type!=="net"){const items=type==="payable"?model.personalObligations.payable:model.personalObligations.receivable;if(!items.length)return `<p class="empty-text">目前沒有${type==="payable"?"應付":"應收"}明細</p>`;return items.map(item=>{const otherId=type==="payable"?item.toPersonId:item.fromPersonId,name=model.memberNames.get(otherId)||"待確認成員";return `<div class="accounting-dialog-row"><span>${type==="payable"?"付給":"向"} <strong>${escape(name)}</strong>${type==="receivable"?" 收款":""}<small>互相扣抵前</small></span><b>${money(item.amount)}</b></div>`;}).join("");}const transfers=(model.personalSettlement&&model.personalSettlement.transfers||[]).filter(item=>item.fromPersonId===personId||item.toPersonId===personId);if(!transfers.length)return `<p class="empty-text">互相扣抵後目前不需付款或收款</p>`;return transfers.map(item=>{const payable=item.fromPersonId===personId,otherId=payable?item.toPersonId:item.fromPersonId,name=model.memberNames.get(otherId)||"待確認成員",claim=(model.activeNetSettlements||[]).find(record=>record.fromPersonId===item.fromPersonId&&record.toPersonId===item.toPersonId&&record.status==="payment_claimed"),action=netSettlementAction(model,item,claim);return `<div class="accounting-dialog-row"><span>${payable?"付給":"向"} <strong>${escape(name)}</strong>${payable?"":" 收款"}<small>${claim?"已付款，等待收款方確認":"互相扣抵後"}</small></span><b>${money(item.amount)}</b>${action}</div>`;}).join("");
  }
  function buildDashboardHtml(model) {
    const netTotal=(model.personalSettlement.payable||0)+(model.personalSettlement.receivable||0),netDirection=model.personalSettlement.payable?"互抵後應付":model.personalSettlement.receivable?"互抵後應收":"已互抵完成";
    const summary=`<div class="accounting-pending-grid"><button type="button" class="accounting-summary-button" data-settlement-dialog="payable"><span>我欠誰</span><b>${money(model.personalObligations.payableTotal)}</b><small>查看原始應付</small></button><button type="button" class="accounting-summary-button" data-settlement-dialog="receivable"><span>誰欠我</span><b>${money(model.personalObligations.receivableTotal)}</b><small>查看原始應收</small></button><button type="button" class="accounting-summary-button" data-settlement-dialog="net"><span>互抵後總額</span><b>${money(netTotal)}</b><small>${netDirection}</small></button></div>`;
    const original=`<div class="accounting-pending-grid"><span>我還要付 <b>${money(model.personalSettlement.payable)}</b></span><span>別人還欠我 <b>${money(model.personalSettlement.receivable)}</b></span><span>等待我確認 <b>${model.counts.paymentConfirmation||0}</b></span></div>`;
    const dialog=`<dialog id="accountingSettlementDialog" class="accounting-settlement-dialog"><div class="accounting-dialog-heading"><div><h4 id="accountingSettlementDialogTitle">款項明細</h4><p id="accountingSettlementDialogTotal"></p></div><button type="button" id="accountingSettlementDialogClose" aria-label="關閉">×</button></div><div id="accountingPayableRows" hidden>${settlementDialogRows(model,"payable")}</div><div id="accountingReceivableRows" hidden>${settlementDialogRows(model,"receivable")}</div><div id="accountingNetRows" hidden>${settlementDialogRows(model,"net")}</div></dialog>`;
    return buildDashboardHtmlBase(model).replace(original,summary+dialog).replace(netSettlementHtml(model),"");
  }
  window.JLYAccountingRender = { buildShellHtml, buildDashboardHtml, statusLabel, netSettlementHtml };
})();
