(function () {
  "use strict";
  const escape = value => String(value == null ? "" : value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const money = value => `$${Number(value || 0).toLocaleString("zh-TW")}`;
  function buildShellHtml() {
    return `<section class="card accounting-card" id="accountingSection"><div class="accounting-heading"><div><h3>💰 車團帳務</h3><p>正在載入帳務資料…</p></div></div></section>`;
  }
  function statusLabel(transaction) {
    if (transaction.splitStatus === "pending") return "🟡 待分帳";
    if (transaction.splitStatus === "completed") return "✓ 分帳完成";
    return "分帳中";
  }
  function splitRows(item, model) {
    if (item.splitStatus === "pending") return "";
    const source=(item.splits||item.shares||[]).filter(split=>model.detailMode||split.personId===model.viewPersonId||item.paidBy===model.viewPersonId);
    const byPerson=new Map();
    source.forEach((split,index)=>{const personId=String(split.personId||split.memberId||split.playerId||"").trim()||`unknown-${index}`,rows=byPerson.get(personId)||[];rows.push(split);byPerson.set(personId,rows);});
    const groups=[...byPerson.entries()].map(([personId,rows])=>({personId,rows,name:model.memberNames.get(personId)||rows[0].displayName||"成員"}));
    const nameCounts=groups.reduce((map,group)=>(map.set(group.name,(map.get(group.name)||0)+1),map),new Map());
    const nameOrdinals=new Map();
    return groups.map(group=>{const ordinal=(nameOrdinals.get(group.name)||0)+1;nameOrdinals.set(group.name,ordinal);const duplicated=group.rows.length>1,total=group.rows.reduce((sum,row)=>sum+Number(row.amount||0),0),sameName=nameCounts.get(group.name)>1,name=sameName?`${group.name}（成員 ${ordinal}）`:group.name,detail=duplicated?`<small class="accounting-split-warning">同一成員有 ${group.rows.length} 筆分帳資料，請確認來源</small>`:"";return `<div class="accounting-split-row" data-split-person-id="${escape(group.personId)}"><span>${escape(name)}${detail}</span><b>${duplicated?group.rows.map(row=>money(row.amount)).join(" + "):money(total)}</b></div>`;}).join("");
  }
  function buildDashboardHtmlLegacy(model) {
    const netSettlement = netSettlementHtml(model);
    const counts = model.counts, members = model.members || [];
    const recent = netSettlement + ((model.transactions || []).map((item,index) => `<article class="accounting-entry" data-transaction-id="${escape(item.transactionId)}" data-filter-state="${escape(model.getFilterState(item))}"${index>=5?" hidden":""}><div class="accounting-entry-summary"><div><strong>${escape(item.title || item.description || "未命名帳目")}</strong><small>付款人：${escape(model.memberNames.get(item.paidBy || item.payerMemberId) || item.payerDisplayName || "待確認")}</small></div><div><b>${money(item.amount)}</b><span>${statusLabel(item)}</span>${item.splitStatus==="pending"?`<button type="button" class="accounting-split-open" data-transaction-id="${escape(item.transactionId)}">分帳</button>`:""}</div></div><div class="accounting-split-list">${splitRows(item,model)}</div></article>`).join("") || `<p class="empty-text">目前沒有帳目</p>`);
    const options = members.map(member => `<option value="${escape(member.personId)}"${member.personId===model.currentPersonId?" selected":""}>${escape(member.displayName)}</option>`).join("");
    return `<div class="accounting-heading"><div><h3>💰 車團帳務</h3><p>待處理 ${counts.total}</p></div><button type="button" id="accountingQuickOpen">＋ 快速記帳</button></div><div class="accounting-pending-grid"><span>待分帳 <b>${counts.pendingSplit}</b></span><span>待付款 <b>${counts.paymentDue}</b></span><span>待確認收款 <b>${counts.paymentConfirmation}</b></span></div><form id="accountingQuickForm" class="accounting-quick-form" hidden><h4>快速記帳</h4><label>項目<input id="accountingTitle" maxlength="80" required placeholder="例如：晚餐"></label><label>金額<input id="accountingAmount" type="number" min="1" step="1" inputmode="numeric" required></label><label>付款人<select id="accountingPaidBy" required>${options}</select></label><p id="accountingFormStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSave">記下來</button><button type="button" id="accountingCancel">取消</button></div></form><form id="accountingSplitForm" class="accounting-quick-form" hidden><h4 id="accountingSplitTitle">分帳</h4><input type="hidden" id="accountingSplitTransactionId"><label>分帳方式<select id="accountingSplitMode"><option value="equal">平均分帳</option><option value="custom">自訂金額</option></select></label><div class="accounting-member-heading"><span>參與成員</span><button type="button" id="accountingSelectAll" class="accounting-select-all">取消全選</button></div><fieldset class="accounting-member-list">${members.map(member=>`<label><input type="checkbox" name="splitMember" value="${escape(member.personId)}" checked><span>${escape(member.displayName)}</span><input class="accounting-custom-amount" data-person-id="${escape(member.personId)}" type="number" min="0" step="1" inputmode="numeric" hidden></label>`).join("")}</fieldset><p id="accountingSplitStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSplitSave">完成分帳</button><button type="button" id="accountingSplitCancel">取消</button></div></form><div class="accounting-list-heading"><h4 id="accountingListTitle">${model.detailMode?"詳細帳目":"最近帳目"}</h4><button type="button" id="accountingViewAll" class="accounting-view-all">${model.detailMode?"篩選本頁":"查看詳細帳務"}</button></div><nav id="accountingFilters" class="accounting-filters" hidden><button data-filter="all">全部</button><button data-filter="pending">待處理</button><button data-filter="pending_split">待分帳</button><button data-filter="payment_due">待付款</button><button data-filter="payment_confirmation">待確認</button><button data-filter="settled">已結清</button></nav><div class="accounting-entry-list">${recent}</div>${model.detailMode&&model.detailHasMore?`<button type="button" id="accountingLoadMore" class="accounting-view-all">載入下一頁（10 筆）</button>`:""}<p id="accountingFilterEmpty" class="empty-text" hidden>目前沒有符合條件的帳目</p>`;
  }
  function buildDashboardHtmlBase(model) {
    const members=model.members||[],counts=model.counts||{},options=members.map(member=>`<option value="${escape(member.personId)}"${member.personId===model.currentPersonId?" selected":""}>${escape(member.displayName)}</option>`).join("");
    const managerMenu=model.isManager?`<div class="accounting-manager-menu"><button type="button" id="accountingManageToggle" aria-label="${model.managementMode?"離開帳務管理":"進入帳務管理"}">${model.managementMode?"完成":"⋯"}</button></div>`:"";
    const managerPanel=model.managementMode?`<section class="accounting-management-panel"><strong>管理帳務</strong><label>查看成員視角<select id="accountingViewPerson">${members.map(member=>`<option value="${escape(member.personId)}"${member.personId===model.viewPersonId?" selected":""}>${escape(member.displayName)}${member.usesSystem?"":"（未使用系統）"}</option>`).join("")}</select></label><small>只有未使用系統的成員可由主揪代為處理。</small></section>`:"";
    const rows=(model.transactions||[]).filter(item=>model.detailMode||item.splitStatus==="pending"||item.paidBy===model.viewPersonId||(item.splits||[]).some(split=>split.personId===model.viewPersonId)).map((item,index)=>`<article class="accounting-entry" data-transaction-id="${escape(item.transactionId)}" data-filter-state="${escape(model.getFilterState(item))}"${index>=5?" hidden":""}><div class="accounting-entry-summary"><div><strong>${escape(item.title||item.description||"未命名帳目")}</strong><small>付款人：${escape(model.memberNames.get(item.paidBy||item.payerMemberId)||item.payerDisplayName||"待確認")}</small></div><div><b>${money(item.amount)}</b><span>${statusLabel(item)}</span>${item.splitStatus==="pending"?`<button type="button" class="accounting-split-open" data-transaction-id="${escape(item.transactionId)}">分帳</button>`:""}</div></div><div class="accounting-split-list">${splitRows(item,model)}</div></article>`).join("")||`<p class="empty-text">目前沒有與你相關的帳目</p>`;
    return `<div class="accounting-heading"><div><h3>💰 車團帳務</h3><p>${model.managementMode?`正在查看：${escape(model.memberNames.get(model.viewPersonId)||"成員")}`:"我的帳務"}</p></div><div class="accounting-heading-actions"><button type="button" id="accountingQuickOpen">＋ 快速記帳</button>${managerMenu}</div></div>${managerPanel}<div class="accounting-pending-grid"><span>我還要付 <b>${money(model.personalSettlement.payable)}</b></span><span>別人還欠我 <b>${money(model.personalSettlement.receivable)}</b></span><span>等待我確認 <b>${counts.paymentConfirmation||0}</b></span></div><form id="accountingQuickForm" class="accounting-quick-form" hidden><h4>快速記帳</h4><label>項目<input id="accountingTitle" maxlength="80" required></label><label>金額<input id="accountingAmount" type="number" min="1" step="1" required></label><label>付款人<select id="accountingPaidBy" required>${options}</select></label><p id="accountingFormStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSave">記下來</button><button type="button" id="accountingCancel">取消</button></div></form><form id="accountingSplitForm" class="accounting-quick-form" hidden><h4 id="accountingSplitTitle">分帳</h4><input type="hidden" id="accountingSplitTransactionId"><label>分帳方式<select id="accountingSplitMode"><option value="equal">平均分帳</option><option value="custom">自訂金額</option></select></label><div class="accounting-member-heading"><span>參與成員</span><button type="button" id="accountingSelectAll" class="accounting-select-all">取消全選</button></div><fieldset class="accounting-member-list">${members.map(member=>`<label><input type="checkbox" name="splitMember" value="${escape(member.personId)}" checked><span>${escape(member.displayName)}</span><input class="accounting-custom-amount" data-person-id="${escape(member.personId)}" type="number" min="0" step="1" hidden></label>`).join("")}</fieldset><p id="accountingSplitStatus" hidden></p><div class="accounting-form-actions"><button type="submit" id="accountingSplitSave">完成分帳</button><button type="button" id="accountingSplitCancel">取消</button></div></form>${netSettlementHtml(model)}<div class="accounting-list-heading"><h4 id="accountingListTitle">${model.detailMode?"詳細帳目":"最近帳目"}</h4><button type="button" id="accountingViewAll" class="accounting-view-all">${model.detailMode?"篩選本頁":"查看詳細帳務"}</button></div><nav id="accountingFilters" class="accounting-filters" hidden><button data-filter="all">全部</button><button data-filter="pending">待處理</button><button data-filter="settled">已結清</button></nav><div class="accounting-entry-list">${rows}</div>${model.detailMode&&model.detailHasMore?`<button type="button" id="accountingLoadMore" class="accounting-view-all">載入下一頁（10 筆）</button>`:""}<p id="accountingFilterEmpty" class="empty-text" hidden>目前沒有符合條件的帳目</p>`;
  }
  function netSettlementHtml(model) {
    const transfers = model.personalSettlement && model.personalSettlement.transfers || [];
    const rows = transfers.map(transfer => {
      const from = model.memberNames.get(transfer.fromPersonId) || "待確認成員";
      const to = model.memberNames.get(transfer.toPersonId) || "待確認成員";
      return `<li><strong>${escape(from)}</strong><span>付給</span><strong>${escape(to)}</strong><b>${money(transfer.amount)}</b></li>`;
    }).join("");
    return `<section class="accounting-net-settlement"><div><h4>${model.managementMode?"成員結算結果":"我的結算結果"}</h4><small>已將相關未結清帳目互相抵扣</small></div>${rows?`<ul>${rows}</ul>`:`<p>目前沒有需要付款或收款的金額</p>`}</section>`;
  }
  function netSettlementAction(model,item,claim) {
    const receiver=model.membersById.get(item.toPersonId);
    const debtor=model.membersById.get(item.fromPersonId);
    const managerCanConfirm=claim&&model.managementMode&&model.isManager&&receiver&&!receiver.usesSystem;
    if(managerCanConfirm)return `<button type="button" class="accounting-net-action" data-accounting-source-id="${escape(claim.settlementId)}" data-action="manager_confirm" data-settlement-id="${escape(claim.settlementId)}" data-target-person-id="${escape(claim.toPersonId)}">代為確認收款</button>`;
    if(claim&&(model.currentPersonId===claim.fromPersonId||model.currentPersonId===claim.paymentClaimedBy))return `<button type="button" class="accounting-net-action" data-action="withdraw" data-settlement-id="${escape(claim.settlementId)}">撤回付款</button>`;
    if(claim&&model.currentPersonId===claim.toPersonId)return `<button type="button" class="accounting-net-action" data-accounting-source-id="${escape(claim.settlementId)}" data-action="confirm" data-settlement-id="${escape(claim.settlementId)}">確認收款</button>`;
    if(!claim&&item.fromPersonId===model.viewPersonId&&model.currentPersonId===item.fromPersonId){const delegates=(model.members||[]).filter(member=>member.personId!==item.fromPersonId&&member.personId!==item.toPersonId).map(member=>`<option value="${escape(member.personId)}">${escape(member.displayName)}</option>`).join("");return `<div class="accounting-payment-input"><div class="accounting-payment-actions"><button type="button" class="accounting-payment-primary" data-payment-sheet-toggle>付款</button><button type="button" class="accounting-payment-more" data-payment-more-toggle aria-label="其他付款操作">⋯</button></div><div class="accounting-payment-sheet" hidden><strong>支付給：${escape(model.memberNames.get(item.toPersonId)||"收款方")}</strong><small>原應付：${money(item.amount)}</small><label>本次支付<input class="accounting-net-amount" type="number" min="1" max="${item.amount}" step="1" inputmode="numeric" value="${item.amount}"></label><label>備註（選填）<input class="accounting-payment-note" maxlength="120"></label><button type="button" class="accounting-net-action" data-action="claim" data-from-person-id="${escape(item.fromPersonId)}" data-to-person-id="${escape(item.toPersonId)}">確認支付</button></div><div class="accounting-payment-more-menu" hidden>${delegates?`<label>請誰幫忙<select class="accounting-delegate-person"><option value="">請選擇正式成員</option>${delegates}</select></label><label>金額<input class="accounting-net-amount" type="number" min="1" max="${item.amount}" value="${item.amount}"></label><button type="button" class="accounting-delegated-action" data-action="request_delegate" data-from-person-id="${escape(item.fromPersonId)}" data-to-person-id="${escape(item.toPersonId)}">請人代付</button>`:""}<button type="button" data-accounting-source-details>查看來源</button></div></div>`;}
    if(!claim&&model.currentPersonId&&model.currentPersonId!==item.fromPersonId&&model.currentPersonId!==item.toPersonId)return `<div class="accounting-payment-input"><button type="button" class="accounting-payment-more" data-payment-more-toggle aria-label="其他付款操作">⋯</button><div class="accounting-payment-more-menu" hidden><small>替 ${escape(model.memberNames.get(item.fromPersonId)||"成員")} 支付給 ${escape(model.memberNames.get(item.toPersonId)||"收款方")}，原始責任不變</small><label>本次支付<input class="accounting-net-amount" type="number" min="1" max="${item.amount}" step="1" inputmode="numeric" value="${item.amount}"></label><button type="button" class="accounting-delegated-action" data-action="delegated_claim" data-from-person-id="${escape(item.fromPersonId)}" data-to-person-id="${escape(item.toPersonId)}">幫他代付</button></div></div>`;
    if(!claim&&item.fromPersonId===model.viewPersonId&&model.managementMode&&model.isManager&&debtor&&!debtor.usesSystem)return `<div class="accounting-payment-input"><label>代為登記付款金額<input class="accounting-net-amount" type="number" min="1" max="${item.amount}" step="1" inputmode="numeric" placeholder="最多 ${item.amount}"></label><div><button type="button" class="accounting-net-action" data-action="manager_claim" data-from-person-id="${escape(item.fromPersonId)}" data-to-person-id="${escape(item.toPersonId)}">代為登記部分付款</button><button type="button" class="accounting-net-action accounting-pay-full" data-action="manager_claim" data-from-person-id="${escape(item.fromPersonId)}" data-to-person-id="${escape(item.toPersonId)}" data-amount="${item.amount}">代為登記全額</button></div></div>`;
    return "";
  }
  function settlementDialogRows(model,type) {
    const personId=model.viewPersonId;if(type!=="net"){const items=type==="payable"?model.personalObligations.payable:model.personalObligations.receivable;if(!items.length)return `<p class="empty-text">目前沒有${type==="payable"?"應付":"應收"}明細</p>`;return items.map(item=>{const otherId=type==="payable"?item.toPersonId:item.fromPersonId,name=model.memberNames.get(otherId)||"待確認成員",direction=type==="payable"?"付款":"收款",sourceId=item.obligationId||item.sourceId||item.transactionId||"";return `<div class="accounting-dialog-row" data-accounting-source-id="${escape(sourceId)}"><span><strong>${direction}</strong>｜${type==="payable"?"付給":"向"} <strong>${escape(name)}</strong>${type==="receivable"?"收款":""}<small>原始尚未結清${type==="payable"?"應付":"應收"}</small></span><b>${money(item.amount)}</b></div>`;}).join("");}const personal=(model.personalSettlement&&model.personalSettlement.transfers||[]).filter(item=>item.fromPersonId===personId||item.toPersonId===personId),helpable=(model.netSettlement&&model.netSettlement.transfers||[]).filter(item=>item.fromPersonId!==model.currentPersonId&&item.toPersonId!==model.currentPersonId),transfers=[...personal,...helpable.filter(item=>!personal.some(own=>own.fromPersonId===item.fromPersonId&&own.toPersonId===item.toPersonId))];if(!transfers.length)return `<p class="empty-text">互相扣抵後目前不需付款或收款</p>`;return transfers.map(item=>{const payable=item.fromPersonId===personId,otherId=payable?item.toPersonId:item.fromPersonId,name=model.memberNames.get(otherId)||"待確認成員",claim=(model.activeNetSettlements||[]).find(record=>record.fromPersonId===item.fromPersonId&&record.toPersonId===item.toPersonId&&record.status==="payment_claimed"),action=netSettlementAction(model,item,claim),amount=claim?claim.amount:item.amount,direction=payable?"付款":item.toPersonId===personId?"收款":"協助",sourceId=claim&&claim.settlementId||item.obligationId||item.sourceId||"",paymentState=claim?"processing":payable?"payable":"processing";return `<div class="accounting-dialog-row" data-payment-state="${paymentState}" data-accounting-source-id="${escape(sourceId)}"><span><strong>${direction}</strong>｜${payable?"付給":item.toPersonId===personId?"向":"可代付："} <strong>${escape(name)}</strong>${payable?"":item.toPersonId===personId?"收款":""}<small>${claim?`已申報 ${money(claim.amount)}，等待確認`:"同一對 Person 互抵後"}</small></span><b>${money(amount)}</b>${action}</div>`;}).join("");
  }
  function settlementHistoryHtml(model) {
    const rows=(model.settlementHistory||[]).map(item=>{const debtorId=item.debtorPersonId||item.fromPersonId,payerId=item.paidBy||item.paymentClaimedBy||debtorId,from=model.memberNames.get(debtorId)||"待確認成員",payer=model.memberNames.get(payerId)||"待確認成員",to=model.memberNames.get(item.receiverPersonId||item.toPersonId)||"待確認成員",paymentText=payerId&&debtorId&&payerId!==debtorId?`<strong>${escape(payer)}</strong> 代 <strong>${escape(from)}</strong> 支付給 <strong>${escape(to)}</strong>`:`<strong>${escape(from)}</strong> 付款給 <strong>${escape(to)}</strong>`,status=item.status==="settled"?"已結清":item.status==="payment_claimed"?"已付款，待確認":item.status==="withdrawn"?"已撤回":item.status||"已記錄",time=item.updatedAt||item.createdAt||"";return `<li><span>${paymentText}<small>${escape(status)}${time?`｜${escape(time)}`:""}</small></span><b>${money(item.amount)}</b></li>`;}).join("");
    return `<section class="accounting-settlement-history"><div class="accounting-list-heading"><h4>付款／收款與核銷紀錄</h4><small>最近 ${rows?(model.settlementHistory||[]).length:0} 筆</small></div>${rows?`<ul>${rows}</ul>`:`<p class="empty-text">目前沒有付款或核銷紀錄</p>`}</section>`;
  }
  function pendingActionHtml(model,item) {
    const type=item.actionType||"accounting_issue",amountText=item.amount?money(item.amount):"",responsible=model.memberNames.get(item.responsiblePersonId)||"待處理成員",otherId=item.toPersonId||item.receiverPersonId||item.fromPersonId||"",other=model.memberNames.get(otherId)||"",labels={pending_split:"尚未分帳",payment_due:"待付款",payment_confirmation:"已申報付款，待確認收到",settlement_rejected:"付款申報被退回",delegated_payment_acceptance:"待回覆代付請求",delegated_payment_due:"已接受代付，待實際付款",accounting_issue:"帳務待確認"},target=type==="pending_split"?"transactions":"people",targetId=item.transactionId||"";
    return `<article class="accounting-pending-index-row"><span><strong>${escape(responsible)}${other?` → ${escape(other)}`:""}${amountText?` ${amountText}`:""}</strong><small>${escape(labels[type]||type)}</small></span><button type="button" data-accounting-pending-action data-action-type="${escape(type)}" data-responsible-person-id="${escape(item.responsiblePersonId||"")}" data-from-person-id="${escape(item.fromPersonId||item.debtorPersonId||"")}" data-to-person-id="${escape(item.toPersonId||item.receiverPersonId||"")}" data-transaction-id="${escape(item.transactionId||"")}" data-settlement-id="${escape(item.settlementId||"")}" data-request-id="${escape(item.requestId||"")}" data-source-id="${escape(item.sourceId||targetId)}" data-source-type="${escape(item.sourceType||"")}">${type==="payment_confirmation"?"去確認":type==="pending_split"?"去分帳":"去處理"}</button></article>`;
  }
  function buildDashboardHtml(model) {
    const netTotal=(model.personalSettlement.payable||0)+(model.personalSettlement.receivable||0),netDirection=model.personalSettlement.payable?"互抵後應付":model.personalSettlement.receivable?"互抵後應收":"已互抵完成";
    const hasAccountingData=(model.transactions||[]).length>0||(model.personalObligations.payableTotal||0)>0||(model.personalObligations.receivableTotal||0)>0||(model.activeNetSettlements||[]).length>0;
    const summary=`<div class="accounting-pending-grid"><button type="button" class="accounting-summary-button" data-settlement-dialog="payable"><span>我欠誰</span><b>${money(model.personalObligations.payableTotal)}</b><small>原始尚未結清應付</small></button><button type="button" class="accounting-summary-button" data-settlement-dialog="receivable"><span>誰欠我</span><b>${money(model.personalObligations.receivableTotal)}</b><small>原始尚未結清應收</small></button><button type="button" class="accounting-summary-button" data-settlement-dialog="net"><span>互抵後總額</span><b>${money(netTotal)}</b><small>${netDirection}</small></button></div>`;
    const original=`<div class="accounting-pending-grid"><span>我還要付 <b>${money(model.personalSettlement.payable)}</b></span><span>別人還欠我 <b>${money(model.personalSettlement.receivable)}</b></span><span>等待我確認 <b>${model.counts.paymentConfirmation||0}</b></span></div>`;
    const dialog=`<dialog id="accountingSettlementDialog" class="accounting-settlement-dialog"><div class="accounting-dialog-heading"><div><h4 id="accountingSettlementDialogTitle">款項明細</h4><p id="accountingSettlementDialogTotal"></p></div><button type="button" id="accountingSettlementDialogClose" aria-label="關閉">×</button></div><div id="accountingPayableRows" hidden>${settlementDialogRows(model,"payable")}</div><div id="accountingReceivableRows" hidden>${settlementDialogRows(model,"receivable")}</div><div id="accountingNetRows" hidden>${settlementDialogRows(model,"net")}</div></dialog>`;
    const detailStart='<div class="accounting-list-heading"><h4 id="accountingListTitle">',detailEnd='<p id="accountingFilterEmpty" class="empty-text" hidden>目前沒有符合條件的帳目</p>';
    const detailToggle=`<button type="button" id="accountingDetailsToggle" class="accounting-details-toggle" data-details-loaded="${model.detailMode?"true":"false"}" aria-expanded="${model.detailMode?"true":"false"}"${hasAccountingData?"":" hidden"}>${model.detailMode?"收起帳務明細":"展開帳務明細"}</button>`;
    const draftOptions=(model.members||[]).map(member=>`<option value="${escape(member.personId)}">${escape(member.displayName)}</option>`).join("");
    const draftRows=(model.pendingDrafts||[]).map(draft=>`<form class="accounting-draft-row" data-draft-id="${escape(draft.draftId)}"><div><strong>${escape(draft.title)}</strong><small>LINE 輸入付款人：${escape(draft.payerInput||"未指定")}</small></div><label>金額<input name="amount" type="number" min="1" value="${Number(draft.amount)||0}" required></label><label>付款人<select name="paidBy" required><option value="">請選擇</option>${draftOptions}</select></label><div class="accounting-form-actions"><button type="submit">確認入帳</button><button type="button" data-draft-dismiss>刪除</button></div></form>`).join("");
    const drafts=model.isManager&&draftRows?`<section class="accounting-drafts"><div class="accounting-list-heading"><h4>待確認記帳</h4><b>${model.pendingDrafts.length}</b></div><div>${draftRows}</div></section>`:"";
    const delegateRequests=(model.pendingActions||[]).filter(item=>item.actionType==="delegated_payment_acceptance"),delegatePayments=(model.pendingActions||[]).filter(item=>item.actionType==="delegated_payment_due"),delegateRows=delegateRequests.map(item=>`<article class="accounting-entry accounting-delegate-request" data-accounting-source-id="${escape(item.requestId)}"><div class="accounting-entry-summary"><div><strong>請人代付</strong><small>${escape(model.memberNames.get(item.debtorPersonId)||"成員")} 請你代付給 ${escape(model.memberNames.get(item.receiverPersonId)||"收款方")}</small></div><b>${money(item.amount)}</b></div><div class="accounting-form-actions"><button type="button" class="accounting-delegated-action" data-action="accept_delegate" data-request-id="${escape(item.requestId)}">接受</button><button type="button" class="accounting-delegated-action" data-action="reject_delegate" data-request-id="${escape(item.requestId)}">拒絕</button></div></article>`).join("")+delegatePayments.map(item=>`<article class="accounting-entry accounting-delegate-request" data-accounting-source-id="${escape(item.requestId)}"><div class="accounting-entry-summary"><div><strong>已接受代付</strong><small>待支付給 ${escape(model.memberNames.get(item.receiverPersonId)||"收款方")}</small></div><b>${money(item.amount)}</b></div><div class="accounting-payment-sheet"><label>本次支付<input class="accounting-net-amount" type="number" min="1" max="${item.amount}" value="${item.amount}"></label><button type="button" class="accounting-delegated-action" data-action="pay_accepted_delegate" data-request-id="${escape(item.requestId)}">付款</button></div></article>`).join("");
    const pendingTransactions=(model.transactions||[]).filter(item=>item&&item.status!=="deleted"&&item.splitStatus==="pending"),pendingSplitCount=pendingTransactions.length,pendingDraftCount=model.isManager?(model.pendingDrafts||[]).length:0,formalPending=(model.pendingActions||[]).filter(item=>!['pending_split','delegated_payment_acceptance','delegated_payment_due'].includes(item.actionType)),pendingTotal=pendingSplitCount+pendingDraftCount+delegateRequests.length+delegatePayments.length+formalPending.length;
    const pendingRows=pendingTransactions.map(item=>`<article class="accounting-entry accounting-pending-entry" data-transaction-id="${escape(item.transactionId)}"><div class="accounting-entry-summary"><div><strong>${escape(item.title||item.description||"未命名帳目")}</strong><small>付款人：${escape(model.memberNames.get(item.paidBy||item.payerMemberId)||item.payerDisplayName||"尚未確認")}</small></div><div><b>${money(item.amount)}</b><span>🟡 待分帳</span><button type="button" data-accounting-pending-action data-action-type="pending_split" data-transaction-id="${escape(item.transactionId)}" data-source-id="${escape(item.transactionId)}">去分帳</button></div></div></article>`).join("");
    const attention=pendingTotal?`<section class="accounting-attention-section"><button type="button" id="accountingAttention" class="accounting-attention" aria-expanded="false"><span>⚠️ 待處理 ${pendingTotal} 筆</span><small>查看目前真正輪到你處理的帳務</small><b>展開 ›</b></button><div id="accountingPendingBody" hidden>${pendingRows}${formalPending.map(item=>pendingActionHtml(model,item)).join("")}${drafts}${delegateRows}</div></section>`:"";
    let html=buildDashboardHtmlBase(model).replace('<div class="accounting-pending-grid">',`<div id="activityFeeMount"></div>${attention}<div class="accounting-pending-grid">`).replace(original,hasAccountingData?summary+dialog:"").replace(netSettlementHtml(model),"");
    html=html.replace(detailStart,`${detailToggle}<section id="accountingDetails"${model.detailMode?"":" hidden"}>${detailStart}`).replace(detailEnd,`${detailEnd}${model.detailMode?settlementHistoryHtml(model):""}</section>`);
    return html;
  }
  window.JLYAccountingRender = { buildShellHtml, buildDashboardHtml, statusLabel, netSettlementHtml };
})();
